<a href="https://colab.research.google.com/github/ashritasubudhi/git1/blob/main/Ashrita_Subudhi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing Libraries:**

In [ ]:
import pandas as pd
import numpy as np

## **Exploring the Data:**

The data we will use for this example is the Iris dataset,a classicsal dataset in machine learning and statistics.

In [ ]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

load_Iris contains key values

In [ ]:
print("Key of iris_dataset: \n{}".format(iris_dataset.keys()))



Key of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Lets see what all these are!!

Dataset is represented by 'DESCR'.

In [ ]:
val=iris_dataset['DESCR']
start_val=val[:200]
print(start_val+ "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


The species of flowers we want to predict are 'setosa' , 'versicolor' and 'virginica'

In [ ]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


Next one is Feature names.

In [ ]:
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


The data fields:

In [ ]:
print("Type of data: \n{}".format(type(iris_dataset['data'])))

Type of data: 
<class 'numpy.ndarray'>


Measurements of each flower:

In [ ]:
print("Shapeof data: {}".format(iris_dataset['data'].shape))

Shapeof data: (150, 4)


Feature values of first five samples:

In [ ]:
print("First five columns: \n{}".format(iris_dataset['data'][:5]))

First five columns: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Target array contains the species of each flowers that were measured.

In [ ]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


it contains one entry per flower.

In [ ]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [ ]:
print("Target: \n{}".format(iris_dataset['target']))

Target: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


0 means setosa

1 means versicolor

2 means virginica

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(
                                  iris_dataset['data'], iris_dataset['target'],random_state=0)

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

As we move on:

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making Predictions:**

In [ ]:
X_new=np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))
X_new.shape: (1,4) 

X_new.shape: (1, 4)


We call the predict method of knn object:

In [ ]:
prediction=knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Prediction target name: {}".format(
iris_dataset['target_names'][prediction]))

Prediction: [0]
Prediction target name: ['setosa']


**Evaluating the Model**

In [ ]:
y_pred=knn.predict(X_test)
print("Test set predictions:\n{}".format(y_pred))

Test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [1]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

NameError: ignored

End of code